### ISSUE TITLE
Cannot install from repo

### ISSUE THREAD

**Issue by zbee** [serifine/XIV-Chat-Tools#28]
**I'm submitting a bug report**

* **Plugin Version:**
2.5.2

**Current behavior:**

Attempt to install from `https://raw.githubusercontent.com/serifine/XIV-Chat-Tools/main/repo.json` fails with error:
```shell
06:46:36.299 | INF | [LOCALPLUGIN] Loading ChatTools.dll
06:46:36.299 | ERR | [LOCALPLUGIN] Error while loading "ChatTools"
	System.ArgumentException: Value must exist (Parameter 'mainAssemblyPath')
	   at Dalamud.Plugin.Internal.Loader.LoaderConfig..ctor(String mainAssemblyPath) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\LoaderConfig.cs:line 29
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.EnsureLoader() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 612
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 318
06:46:36.299 | ERR | [PLUGINW] Plugin installer threw an unexpected error
	System.ArgumentException: Value must exist (Parameter 'mainAssemblyPath')
	   at Dalamud.Plugin.Internal.Loader.LoaderConfig..ctor(String mainAssemblyPath) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\LoaderConfig.cs:line 29
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.EnsureLoader() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 612
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 318
	   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\PluginManager.cs:line 1650
	   at Dalamud.Plugin.Internal.PluginManager.InstallPluginInternalAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Stream zipStream, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\PluginManager.cs:line 1524
	   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\PluginManager.cs:line 844

```

**Expected/desired behavior:**

No error on install.

**Comment by serifine** [comment]
This was an error from a large rework I am doing for this plugin that is almost a ground up rewrite. This included a name change and the repo file was caught in the crosshairs. That work really should have been done on a separate branch 😅 

This should be resolved now.

**Comment by serifine** [comment]
There was a large rework of the entire plugin which caused the delay combined with not having much time to work on this. However there is a new version live under the name "Chat Tools".
